# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Layer rules ########
layerrule = blur 1, xray 0, match:namespace quickshell:dock
layerrule = blur 1, xray 0, match:namespace quickshell:macClock
layerrule = blur on, xray off, ignore_alpha 0.5, match:namespace ^quickshell:notificationPopup$

# ######## Window rules ########

# Todoist always floating
windowrule = float on, match:class ^Todoist$

# qimgv always floating
windowrule = float on, match:class ^qimgv$

# Cairo Dock
windowrule = float on, match:class ^cairo-dock$
windowrule = pin on, match:class ^cairo-dock$
windowrule = no_blur on, match:class ^cairo-dock$
windowrule = no_shadow on, match:class ^cairo-dock$

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland yes