#!/bin/bash
# Generated by apply-we-wallpaper.sh
# Restores Wallpaper Engine wallpaper after reboot

WORKSHOP_BASE="/home/brunno/.local/share/Steam/steamapps/workshop/content/431960"
ASSETS_DIR="/home/brunno/.local/share/Steam/steamapps/common/wallpaper_engine/assets"
SHELL_CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/illogical-impulse/config.json"

# Read workshop ID from config
if [ ! -f "$SHELL_CONFIG_FILE" ]; then
    echo "Config file not found: $SHELL_CONFIG_FILE"
    exit 1
fi

IS_ACTIVE=$(jq -r '.background.wallpaperEngine.isActive // false' "$SHELL_CONFIG_FILE")
if [ "$IS_ACTIVE" != "true" ]; then
    echo "WE wallpaper not active"
    exit 0
fi

WORKSHOP_ID=$(jq -r '.background.wallpaperEngine.workshopId // ""' "$SHELL_CONFIG_FILE")
if [ -z "$WORKSHOP_ID" ]; then
    echo "No workshop ID in config"
    exit 0
fi

WORKSHOP_PATH="$WORKSHOP_BASE/$WORKSHOP_ID"

if [ ! -d "$WORKSHOP_PATH" ]; then
    echo "Workshop directory not found: $WORKSHOP_PATH"
    exit 1
fi

# Get monitors
MONITORS=$(hyprctl monitors -j | jq -r '.[] | .name')

# Read sound settings from config
ENABLE_SOUND=$(jq -r '.background.wallpaperEngine.enableSound // false' "$SHELL_CONFIG_FILE")
ENABLE_AUDIO_PROC=$(jq -r '.background.wallpaperEngine.enableAudioProcessing // true' "$SHELL_CONFIG_FILE")

# Apply wallpaper
CMD="linux-wallpaperengine"
CMD="$CMD --assets-dir \"$ASSETS_DIR\""
CMD="$CMD --fps 60"
if [ "$ENABLE_SOUND" != "true" ]; then
    CMD="$CMD --silent"
fi
if [ "$ENABLE_AUDIO_PROC" != "true" ]; then
    CMD="$CMD --no-audio-processing"
fi

for monitor in $MONITORS; do
    CMD="$CMD --screen-root $monitor"
done

CMD="$CMD \"$WORKSHOP_PATH\""

eval "$CMD" &

echo "Wallpaper Engine wallpaper restored: $WORKSHOP_ID"
